name: Local Config
version: 0.0.1
schema: v1

models:
  - name: Local Chat
    provider: ollama
    model: qwen3-vl:8b
    roles:
      - chat

  - name: Local Autocomplete
    provider: ollama
    model: qwen3-vl:8b
    roles:
      - autocomplete